Repository zendframework/zend-diactoros, pull requests merged in 2018-12, with the labels that each got.

#339 Updated export-ignores to cleanup release
  .gitattributes
Labels: enhancement

#340 Adds namespaces in documentation section for custom responses
  docs/book/v2/custom-responses.md
Labels: documentation, enhancement

#341 Updates configuration for MkDocs
  mkdocs.yml
Labels: bug, documentation
